#!/bin/sh
# Powered by Apad.pro
# https://apad.pro/easymosdns

mosdns_working_dir="/etc/mosdns"
temp_dir="$(mktemp -d)"

# Download the required files from GitHub
wget -O "$temp_dir"/china_domain_list.txt https://fastly.jsdelivr.net/gh/pmkol/easymosdns@rules/china_domain_list.txt
wget -O "$temp_dir"/gfw_domain_list.txt https://fastly.jsdelivr.net/gh/pmkol/easymosdns@rules/gfw_domain_list.txt
wget -O "$temp_dir"/cdn_domain_list.txt https://fastly.jsdelivr.net/gh/pmkol/easymosdns@rules/cdn_domain_list.txt
wget -O "$temp_dir"/china_ip_list.txt https://fastly.jsdelivr.net/gh/pmkol/easymosdns@rules/china_ip_list.txt
wget -O "$temp_dir"/gfw_ip_list.txt https://fastly.jsdelivr.net/gh/pmkol/easymosdns@rules/gfw_ip_list.txt
wget -O "$temp_dir"/ad_domain_list.txt https://fastly.jsdelivr.net/gh/pmkol/easymosdns@rules/ad_domain_list.txt

# Copy the downloaded files to the mosdns working directory
cp -rf "$temp_dir"/* $mosdns_working_dir/rules

# Clean up the temporary directory
rm -rf "$temp_dir"

# Print a success message
echo 'Update successful'
